### ISSUE TITLE
Missing Dependency "flash_attn" When Running on H100 Instance

### ISSUE THREAD

**Issue by KieranRatcliffeInvertedAI** [nvidia-cosmos/cosmos-transfer2.5#36]
I followed all the installation procedures and ensured I have the required specifications but I am receiving the following error when running the basic example: 

`python examples/inference.py -i assets/robot_example/depth/robot_depth_spec.json -o outputs/depth`

Here is the error traceback:
`(cosmos-transfer2) ubuntu:~/cosmos-transfer2.5$ python examples/inference.py -i assets/robot_example/depth/robot_depth_spec.json -o outputs/depth
[10-24 22:50:08|INFO|cosmos_transfer2/_src/imaginaire/utils/checkpoint_db.py:171:path] Downloading checkpoint nvidia/Cosmos-Transfer2.5-2B/general/edge(ecd0ba00-d598-4f94-aa09-e8627899c431)
[10-24 22:50:08|INFO|cosmos_transfer2/_src/imaginaire/utils/checkpoint_db.py:96:_download] Downloading checkpoint file from Hugging Face with {'repo_id': 'nvidia/Cosmos-Transfer2.5-2B', 'repo_type': 'model', 'revision': 'bd963eabcfc2d61dc4ea365cacf41d45ac480aa5', 'filename': 'general/edge/ecd0ba00-d598-4f94-aa09-e8627899c431_ema_bf16.pt'}
[10-24 22:50:08|INFO|cosmos_transfer2/init.py:91:_init_log_files] Log saved to outputs/depth/console.log
[10-24 22:50:08|INFO|cosmos_transfer2/_src/imaginaire/utils/checkpoint_db.py:171:path] Downloading checkpoint nvidia/Cosmos-Guardrail1(9c7b7da4-2d95-45bb-9cb8-2eed954e9736)
[10-24 22:50:08|INFO|cosmos_transfer2/_src/imaginaire/utils/checkpoint_db.py:131:_download] Downloading checkpoint from Hugging Face with {'repo_id': 'nvidia/Cosmos-Guardrail1', 'repo_type': 'model', 'revision': 'd6d4bfa899a71454a700907664f3e88f503950cf', 'allow_patterns': ['*']}
Fetching 102 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 102/102 [00:00<00:00, 2318.00it/s]
/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:174: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
flash_attn_2 not available
Traceback (most recent call last):
  File "/home/ubuntu/cosmos-transfer2.5/examples/inference.py", line 63, in <module>
    main(args)
  File "/home/ubuntu/cosmos-transfer2.5/examples/inference.py", line 49, in main
    from cosmos_transfer2.inference import Control2WorldInference
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/inference.py", line 26, in <module>
    from cosmos_transfer2._src.transfer2.inference.inference_pipeline import ControlVideo2WorldInference
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/transfer2/inference/inference_pipeline.py", line 27, in <module>
    from cosmos_transfer2._src.predict2.models.video2world_model import NUM_CONDITIONAL_FRAMES_KEY
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/predict2/models/video2world_model.py", line 28, in <module>
    from cosmos_transfer2._src.predict2.configs.video2world.defaults.conditioner import Video2WorldCondition
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/predict2/configs/video2world/defaults/conditioner.py", line 33, in <module>
    from cosmos_transfer2._src.predict2.models.video2world_wan2pt1_model import WAN2PT1_I2V_COND_LATENT_KEY
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/predict2/models/video2world_wan2pt1_model.py", line 21, in <module>
    from cosmos_transfer2._src.predict2.models.text2world_model import Text2WorldCondition
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/predict2/models/text2world_model.py", line 55, in <module>
    from cosmos_transfer2._src.predict2.text_encoders.text_encoder import TextEncoder, TextEncoderConfig
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/predict2/text_encoders/text_encoder.py", line 28, in <module>
    from cosmos_transfer2._src.predict2.text_encoders.reason1 import QwenVLBaseModel
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/predict2/text_encoders/reason1.py", line 26, in <module>
    from cosmos_transfer2._src.reason1.models.vlm_qwen import QwenModel
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/reason1/models/vlm_qwen.py", line 25, in <module>
    from cosmos_transfer2._src.reason1.networks.qwen2_5_vl import Qwen2_5_VisionTransformerPretrainedModel, Qwen2_5_VLModel
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/reason1/networks/qwen2_5_vl.py", line 68, in <module>
    assert is_flash_attn_2_available(), "flash_attn_2 not available. run pip install flash_attn"
AssertionError: flash_attn_2 not available. run pip install flash_attn`

To confirm, the instance is:
Ubuntu 24.04.3 LTS, x86-64 architecture, and running Python 3.10
Here is the result of running nvidia-smi, note this instance has 8xH100 GPUs, 200 vCPUs, 940GB RAM, 20.0TB SSD, and 500Gi root disk:
`ubuntu:~/cosmos-transfer2.5$ nvidia-smi
Fri Oct 24 23:07:30 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          Off |   00000000:0A:00.0 Off |                    0 |
| N/A   31C    P0            117W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          Off |   00000000:0B:00.0 Off |                    0 |
| N/A   30C    P0            116W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          Off |   00000000:0C:00.0 Off |                    0 |
| N/A   33C    P0            118W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          Off |   00000000:0D:00.0 Off |                    0 |
| N/A   34C    P0            122W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA H100 80GB HBM3          Off |   00000000:0E:00.0 Off |                    0 |
| N/A   32C    P0            119W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA H100 80GB HBM3          Off |   00000000:0F:00.0 Off |                    0 |
| N/A   30C    P0            117W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA H100 80GB HBM3          Off |   00000000:10:00.0 Off |                    0 |
| N/A   35C    P0            120W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA H100 80GB HBM3          Off |   00000000:11:00.0 Off |                    0 |
| N/A   33C    P0            123W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+`

When I try to install this package, I get errors but that may be a separate issue. For context, I've been able to run the basic example and a rendering with my own data on a single GPU A100 instance and never received an error referencing this "flash_attn" package.

**Comment by aryamancodes** [comment]
Hi there! I just tried a new clone and install and don't see this issue. We pushed a new release early last week with some dependency upgrades, could you please pull the latest version of the code and try re-installing?

**Comment by KieranRatcliffeInvertedAI** [comment]
Here is the output of running that above command:

```
uv run pip list
Package    Version
---------- -------
pip        25.2
setuptools 80.9.0
```

And again I followed all the instructions in the [Setup Guide](https://github.com/nvidia-cosmos/cosmos-transfer2.5/blob/main/docs/setup.md) and I am pretty sure I have met all the requirements.

**Comment by KieranRatcliffeInvertedAI** [comment]
@aryamancodes something else I've found during testing is that instances with single GPU's run the basic example perfectly fine. Though I did get a warning regarding flash_attn before the example ran as expected:
`WARNING:root:Supported flash-attn versions are >= 2.1.1, <= 2.6.3. Found flash-attn 2.8.3.`

My issues is that I am interested in the [Multiview Example](https://github.com/nvidia-cosmos/cosmos-transfer2.5/blob/main/docs/inference_auto_multiview.md) which seems like it requires multiple GPUs so I need this issue to be resolved.

**Comment by KieranRatcliffeInvertedAI** [comment]
I am running the following command on both single and multi GPU instances:

`python examples/inference.py -i assets/robot_example/depth/robot_depth_spec.json -o outputs/depth`

On single-GPU instances, it runs fine. On multi-GPU instances, I get the error from my first message. The documentation made it seem like this command could run on a multi-GPU instance by just using one of the GPUs, is this not true and the error I've been receiving is expected for trying to run this command on a multi-GPU instance?

**Comment by KieranRatcliffeInvertedAI** [comment]
That's what I thought initially. As far as I can tell, NVIDIA Driver Version 580.95.05 should be compatible with CUDA Version 13.0. Furthermore I've run `nvcc --version` to confirm the CUDA version is indeed 13.0, but I still get the same error. 
I'm not sure if this is helpful but all of this experimentation has been done on a virtual machine instances.

**Comment by aryamancodes** [comment]
What happens if you run single gpu using `torchrun` in the multi-gpu environment:
```
torchrun --nproc_per_node=1 --master_port=12341 -m examples.inference -i assets/robot_example/depth/robot_depth_spec.json -o outputs/depth 
```

**Comment by KieranRatcliffeInvertedAI** [comment]
Here is the output of running the above command:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/cosmos-transfer2.5/examples/inference.py", line 58, in <module>
    init_environment()
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/cosmos_oss/init.py", line 160, in init_environment
    _init_distributed()
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/cosmos_oss/init.py", line 120, in _init_distributed
    distributed.init()
  File "/home/ubuntu/cosmos-transfer2.5/cosmos_transfer2/_src/imaginaire/utils/distributed.py", line 66, in init
    torch.cuda.set_device(local_rank)
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 569, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 412, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized
E1029 18:24:13.920000 6588 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 6653) of binary: /home/ubuntu/cosmos-transfer2.5/.venv/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/cosmos-transfer2.5/.venv/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 357, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 143, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/cosmos-transfer2.5/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 277, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples.inference FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-10-29_18:24:13
  host      : vm-2025102909446426
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6653)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Furthermore, to confirm, here is the output of nvidia-smi:

```
$ nvidia-smi
Wed Oct 29 18:25:28 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  |   00000000:0A:00.0 Off |                    0 |
| N/A   33C    P0             56W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          On  |   00000000:0B:00.0 Off |                    0 |
| N/A   32C    P0             53W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB          On  |   00000000:0C:00.0 Off |                    0 |
| N/A   31C    P0             53W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB          On  |   00000000:0D:00.0 Off |                    0 |
| N/A   34C    P0             55W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA A100-SXM4-80GB          On  |   00000000:0E:00.0 Off |                    0 |
| N/A   33C    P0             54W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA A100-SXM4-80GB          On  |   00000000:0F:00.0 Off |                    0 |
| N/A   32C    P0             54W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA A100-SXM4-80GB          On  |   00000000:10:00.0 Off |                    0 |
| N/A   33C    P0             56W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA A100-SXM4-80GB          On  |   00000000:11:00.0 Off |                    0 |
| N/A   34C    P0             51W /  500W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

And the output of nvcc --version:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

Though for this last one, on my single GPU instance, `nvcc --version` showed nothing yet it run nonetheless so I don't know if this last part is necessary but included it here for completion sake.

**Comment by aryamancodes** [comment]
One last check to really make sure it's not an environment thing, can you add `uv run` in front of your run commands. So `uv run python ...` or `uv run torchrun ...`

**Comment by KieranRatcliffeInvertedAI** [comment]
Hi @aryamancodes I followed the instructions you wrote and it still resulted in a failure on a multi-GPU instance. I tried following the same instructions on a single-GPU instance and it worked perfectly fine weirdly enough. Building the docker container took a reasonably short amount of time on the single-GPU instance but on the multi-GPU instance, it took several hours and then failed with the following traceback:

```
~/cosmos-transfer2.5$ docker build --ulimit nofile=131071:131071 -f Dockerfile . -t cosmos-transfer-2.5
[+] Building 8897.6s (12/12) FINISHED                                                                                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 2.51kB                                                                                                                                                   0.0s
 => [internal] load metadata for ghcr.io/astral-sh/uv:0.8.12                                                                                                                             0.3s
 => [internal] load metadata for docker.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04                                                                                                    0.3s
 => [internal] load .dockerignore                                                                                                                                                        0.0s
 => => transferring context: 144B                                                                                                                                                        0.0s
 => [stage-0 1/6] FROM docker.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04@sha256:24c8e3581ea6330038b0d374920721983312627f8adbfcf390bdb4b399d280ed                                      0.0s
 => FROM ghcr.io/astral-sh/uv:0.8.12@sha256:f64ad69940b634e75d2e4d799eb5238066c5eeda49f76e782d4873c3d014ea33                                                                             0.0s
 => [internal] load build context                                                                                                                                                        0.0s
 => => transferring context: 4.13kB                                                                                                                                                      0.0s
 => CACHED [stage-0 2/6] RUN --mount=type=cache,target=/var/cache/apt     --mount=type=cache,target=/var/lib/apt     apt-get update &&     apt-get install -y --no-install-recommends    0.0s
 => CACHED [stage-0 3/6] COPY --from=ghcr.io/astral-sh/uv:0.8.12 /uv /uvx /usr/local/bin/                                                                                                0.0s
 => CACHED [stage-0 4/6] RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin --tag 1.42.4                                          0.0s
 => CACHED [stage-0 5/6] WORKDIR /workspace                                                                                                                                              0.0s
 => ERROR [stage-0 6/6] RUN --mount=type=cache,target=/root/.cache/uv     --mount=type=bind,source=uv.lock,target=uv.lock     --mount=type=bind,source=pyproject.toml,target=pyproje  8897.2s
------                                                                                                                                                                                        
 > [stage-0 6/6] RUN --mount=type=cache,target=/root/.cache/uv     --mount=type=bind,source=uv.lock,target=uv.lock     --mount=type=bind,source=pyproject.toml,target=pyproject.toml     --mount=type=bind,source=.python-version,target=.python-version     --mount=type=bind,source=packages,target=packages     uv sync --locked --no-install-project:                                   
1.453 Downloading cpython-3.10.18-linux-x86_64-gnu (download) (26.5MiB)                                                                                                                       
201.2  Downloading cpython-3.10.18-linux-x86_64-gnu (download)                                                                                                                                
201.4 Using CPython 3.10.18                                                                                                                                                                   
201.4 Creating virtual environment at: .venv
202.6 Resolved 256 packages in 1.18s
202.6    Building sam2==1.1.0
202.9 Downloading nvidia-cusolver-cu12 (248.3MiB)
203.3 Downloading nvidia-cudnn-cu12 (693.2MiB)
203.3 Downloading triton (148.4MiB)
203.3 Downloading xformers (111.6MiB)
203.3 Downloading nvidia-cusparse-cu12 (278.5MiB)
203.3 Downloading nvidia-cublas-cu12 (581.4MiB)
203.3 Downloading nvidia-cusparselt-cu12 (149.5MiB)
203.3 Downloading nvidia-cuda-nvrtc-cu12 (83.9MiB)
203.9 Downloading torch (991.2MiB)
203.9 Downloading natten (345.6MiB)
203.9 Downloading nvidia-cufft-cu12 (184.2MiB)
203.9 Downloading nvidia-nccl-cu12 (192.0MiB)
3467.0 Downloading torch (991.2MiB)
3468.8 Downloading natten (345.6MiB)
8745.6  Downloading natten
8897.0   × Failed to download and build `sam2==1.1.0`
8897.0   ├─▶ Failed to install requirements from `build-system.requires`
8897.0   ├─▶ Failed to download `nvidia-cublas-cu12==12.8.4.1`
8897.0   ├─▶ Failed to extract archive:
8897.0   │   nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl
8897.0   ╰─▶ I/O operation failed during extraction
8897.0   help: `sam2` (v1.1.0) was included because `cosmos-transfer2` (v1.2.0)
8897.0         depends on `sam2`
------
Dockerfile:55
--------------------
  54 |     # Install the project's dependencies using the lockfile and settings
  55 | >>> RUN --mount=type=cache,target=/root/.cache/uv \
  56 | >>>     --mount=type=bind,source=uv.lock,target=uv.lock \
  57 | >>>     --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
  58 | >>>     --mount=type=bind,source=.python-version,target=.python-version \
  59 | >>>     --mount=type=bind,source=packages,target=packages \
  60 | >>>     uv sync --locked --no-install-project
  61 |     
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c uv sync --locked --no-install-project" did not complete successfully: exit code: 1
```

**Comment by pjannaty** [comment]
We upgraded the dependencies in the new release today. Could you give one more try?

**Comment by aryamancodes** [comment]
Can you use `uv sync --extra=cu128`? We haven't fully tested cu13 yet but #68 makes the option available if you want!

**Comment by KieranRatcliffeInvertedAI** [comment]
I already tried that command previously (`uv sync --extra=cu128`) and got the following error message:

```
Resolved 256 packages in 256ms
error: Extra `cu128` is not defined in the project's `optional-dependencies` table
```

**Comment by aryamancodes** [comment]
Hmmm I just re-cloned and `uv sync --extra=cu128` does work. Are you sure you're on the latest version of the code?

**Comment by KieranRatcliffeInvertedAI** [comment]
So I tried running the new installation instructions again after pulling the latest version of the code on a fresh cloud machine. I tried running `uv sync --extra=cu128` and `uv sync --extra=cu130` both on freshly spun up cloud machines with the above GPUs. The installations ran without error but I experienced the same error when trying to run the examples.

**Comment by spectralflight** [comment]
@KieranRatcliffeInvertedAI We have merged a new container based on the nvidia torch container: https://github.com/nvidia-cosmos/cosmos-transfer2.5/blob/main/docs/setup.md#docker-container Could you please see if using this container fixes your issues?

It is using CUDA 13.0/Torch 2.9. 

Example:

```
image_tag=$(docker build -f docker/nightly.Dockerfile -q .)
docker run -it --gpus all --ipc=host --rm -v .:/workspace -v /workspace/.venv -v /root/.cache:/root/.cache $image_tag
python examples/inference.py -i assets/robot_example/depth/robot_depth_spec.json -o outputs/depth
```
